services:
  - type: web
    name: college-project
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9